---
engines:
  bandit:
    exclude_paths:
      - 'tests/**'
      - 'scripts/**'
  prospector:
    exclude_paths:
      - 'tests/**'
      - 'scripts/**'
  opengrep:
    exclude_paths:
      - 'tests/**'
      - 'scripts/**'

exclude_paths:
  - 'dist/**'
  - 'build/**'
  - '*.egg-info/**'
  - 'scripts/**'
