"""Field ordering and labels for text/json/xml renderers."""

from __future__ import annotations

TEXT_FIELD_ORDER: dict[str, list[str]] = {
    "General": [
        "UniqueID",
        "CompleteName",
        "Format",
        "Format_Profile",
        "Format_Version",
        "CodecID",
        "FileSize",
        "Duration",
        "OverallBitRate",
        "FrameRate",
        "Title",
        "Encoded_Application",
        "Encoded_Library",
        "Comment",
        "extra.ErrorDetectionType",
    ],
    "Video": [
        "ID",
        "Format",
        "Format_Info",
        "Format_Profile",
        "HDR_Format",
        "HDR_Format_Compatibility",
        "Format_Settings",
        "Format_Settings_CABAC",
        "Format_Settings_RefFrames",
        "CodecID",
        "CodecID_Info",
        "Duration",
        "BitRate",
        "Width",
        "Width_Original",
        "Height",
        "Height_Original",
        "DisplayAspectRatio",
        "FrameRate_Mode",
        "FrameRate",
        "ColorSpace",
        "ChromaSubsampling",
        "BitDepth",
        "ScanType",
        "Title",
        "Bits_Pixel_Frame",
        "StreamSize",
        "Encoded_Library",
        "Encoded_Library_Settings",
        "Default",
        "Forced",
        "colour_range",
        "colour_primaries",
        "transfer_characteristics",
        "matrix_coefficients",
        "MasteringDisplay_ColorPrimaries",
        "MasteringDisplay_Luminance",
        "MaxCLL",
        "MaxFALL",
        "CodecConfigurationBox",
    ],
    "Audio": [
        "ID",
        "Format",
        "Format_Info",
        "Format_Commercial_IfAny",
        "CodecID",
        "Duration",
        "Source_Duration",
        "Source_Duration_LastFrame",
        "BitRate_Mode",
        "BitRate",
        "Channels",
        "ChannelLayout",
        "SamplingRate",
        "FrameRate",
        "BitDepth",
        "Compression_Mode",
        "Title",
        "StreamSize",
        "Source_StreamSize",
        "Encoded_Library",
        "Language",
        "ServiceKind",
        "Default",
        "Forced",
        "AlternateGroup",
        "extra.dialnorm",
        "extra.dialnorm_Average",
        "extra.dialnorm_Minimum",
        "extra.dialnorm_Maximum",
    ],
    "Text": [
        "ID",
        "Format",
        "CodecID",
        "CodecID_Info",
        "Duration",
        "Duration_End",
        "Compression_Mode",
        "Events_Total",
        "Events_MinDuration",
        "Lines_Count",
        "Lines_MaxCountPerEvent",
        "Title",
        "Encoded_Library",
        "Language",
        "Default",
        "Forced",
    ],
    "Menu": [],
}

TEXT_LABELS: dict[str, str] = {
    "CompleteName": "Complete name",
    "Format_Profile": "Format profile",
    "Format_Version": "Format version",
    "Format_Level": "Format Level",
    "CodecID": "Codec ID",
    "CodecID_Info": "Codec ID/Info",
    "UniqueID": "Unique ID",
    "FileSize": "File size",
    "OverallBitRate": "Overall bit rate",
    "FrameRate": "Frame rate",
    "BitRate": "Bit rate",
    "FrameCount": "Frame count",
    "Encoded_Application": "Writing application",
    "Encoded_Library": "Writing library",
    "Encoded_Library_Name": "Encoded library name",
    "Encoded_Library_Version": "Encoded library version",
    "Encoded_Library_Settings": "Encoding settings",
    "Format_Info": "Format/Info",
    "Format_Settings": "Format settings",
    "Format_Settings_CABAC": "Format settings, CABAC",
    "Format_Settings_RefFrames": "Format settings, Reference frames",
    "StreamOrder": "Stream order",
    "Width_Original": "Original width",
    "Height_Original": "Original height",
    "DisplayAspectRatio": "Display aspect ratio",
    "FrameRate_Mode": "Frame rate mode",
    "ColorSpace": "Color space",
    "ChromaSubsampling": "Chroma subsampling",
    "BitDepth": "Bit depth",
    "ScanType": "Scan type",
    "Bits_Pixel_Frame": "Bits/(Pixel*Frame)",
    "BitRate_Mode": "Bit rate mode",
    "Source_Duration": "Source duration",
    "Source_Duration_LastFrame": "Source_Duration_LastFrame",
    "Source_StreamSize": "Source stream size",
    "Channels": "Channel(s)",
    "SamplingRate": "Sampling rate",
    "Compression_Mode": "Compression mode",
    "Format_AdditionalFeatures": "Commercial name",
    "Format_Commercial_IfAny": "Commercial name",
    "ServiceKind": "Service kind",
    "colour_range": "Color range",
    "matrix_coefficients": "Matrix coefficients",
    "CodecConfigurationBox": "Codec configuration box",
    "HDR_Format": "HDR format",
    "HDR_Format_Compatibility": "HDR format compatibility",
    "MaxCLL": "Maximum Content Light Level",
    "MaxFALL": "Maximum Frame-Average Light Level",
    "colour_primaries": "Color primaries",
    "transfer_characteristics": "Transfer characteristics",
    "MasteringDisplay_ColorPrimaries": "Mastering display color primaries",
    "MasteringDisplay_Luminance": "Mastering display luminance",
    "Title": "Title",
    "Comment": "Comment",
    "Movie": "Movie",
    "Language": "Language",
    "MenuCount": "Menu count",
    "FileExtension": "File extension",
    "VideoCount": "Video count",
    "AudioCount": "Audio count",
    "TextCount": "Text count",
    "File_Created_Date": "File created date",
    "File_Created_Date_Local": "File created date (local)",
    "File_Modified_Date": "File modified date",
    "File_Modified_Date_Local": "File modified date (local)",
    "StreamSize": "Stream size",
    "Source_StreamSize": "Source stream size",
    "ChannelPositions": "Channel positions",
    "ChannelLayout": "Channel layout",
    "AlternateGroup": "Alternate group",
    "Duration_End": "End time",
    "Events_Total": "Count of events",
    "Events_MinDuration": "Minimum duration per event",
    "Lines_Count": "Count of lines",
    "Lines_MaxCountPerEvent": "Maximum count of lines per event",
    "extra.ErrorDetectionType": "ErrorDetectionType",
    "extra.dialnorm": "Dialog Normalization",
    "extra.dialnorm_Average": "dialnorm_Average",
    "extra.dialnorm_Minimum": "dialnorm_Minimum",
    "extra.dialnorm_Maximum": "dialnorm_Maximum",
}

STRUCTURED_FIELD_ORDER: dict[str, list[str]] = {
    "General": [
        "UniqueID",
        "VideoCount",
        "AudioCount",
        "TextCount",
        "MenuCount",
        "FileExtension",
        "Format",
        "Format_Profile",
        "Format_Version",
        "CodecID",
        "CodecID_Compatible",
        "FileSize",
        "Duration",
        "OverallBitRate",
        "FrameRate",
        "FrameCount",
        "StreamSize",
        "Title",
        "Movie",
        "HeaderSize",
        "DataSize",
        "FooterSize",
        "IsStreamable",
        "File_Created_Date",
        "File_Created_Date_Local",
        "File_Modified_Date",
        "File_Modified_Date_Local",
        "Encoded_Application",
        "Encoded_Library",
        "Comment",
    ],
    "Video": [
        "StreamOrder",
        "ID",
        "UniqueID",
        "Format",
        "Format_Profile",
        "Format_Level",
        "Format_Tier",
        "HDR_Format",
        "HDR_Format_Compatibility",
        "Format_Settings_CABAC",
        "Format_Settings_RefFrames",
        "CodecID",
        "Duration",
        "BitRate",
        "Width",
        "Width_Original",
        "Height",
        "Height_Original",
        "Stored_Height",
        "Sampled_Width",
        "Sampled_Height",
        "PixelAspectRatio",
        "DisplayAspectRatio",
        "Rotation",
        "FrameRate_Mode",
        "FrameRate_Mode_Original",
        "FrameRate",
        "FrameRate_Num",
        "FrameRate_Den",
        "FrameCount",
        "ColorSpace",
        "ChromaSubsampling",
        "BitDepth",
        "ScanType",
        "Delay",
        "Delay_Source",
        "StreamSize",
        "Title",
        "Encoded_Library",
        "Encoded_Library_Name",
        "Encoded_Library_Version",
        "Encoded_Library_Settings",
        "Default",
        "Forced",
        "colour_description_present",
        "colour_description_present_Source",
        "colour_range",
        "colour_range_Source",
        "colour_primaries",
        "colour_primaries_Source",
        "transfer_characteristics",
        "transfer_characteristics_Source",
        "matrix_coefficients",
        "matrix_coefficients_Source",
        "MasteringDisplay_ColorPrimaries",
        "MasteringDisplay_ColorPrimaries_Source",
        "MasteringDisplay_Luminance",
        "MasteringDisplay_Luminance_Source",
        "MasteringDisplay_Luminance_Min",
        "MasteringDisplay_Luminance_Max",
        "MaxCLL",
        "MaxCLL_Source",
        "MaxFALL",
        "MaxFALL_Source",
    ],
    "Audio": [
        "StreamOrder",
        "ID",
        "UniqueID",
        "Format",
        "Format_Settings_SBR",
        "Format_AdditionalFeatures",
        "Format_Commercial_IfAny",
        "Format_Settings_Endianness",
        "CodecID",
        "Duration",
        "Source_Duration",
        "Source_Duration_LastFrame",
        "BitRate_Mode",
        "BitRate",
        "Channels",
        "ChannelPositions",
        "ChannelLayout",
        "SamplesPerFrame",
        "SamplingRate",
        "SamplingCount",
        "FrameRate",
        "FrameCount",
        "Source_FrameCount",
        "BitDepth",
        "Compression_Mode",
        "Delay",
        "Delay_Source",
        "Video_Delay",
        "StreamSize",
        "Source_StreamSize",
        "Title",
        "Encoded_Library",
        "Language",
        "ServiceKind",
        "Default",
        "Forced",
        "AlternateGroup",
    ],
    "Text": [
        "StreamOrder",
        "ID",
        "UniqueID",
        "Format",
        "CodecID",
        "Duration",
        "Duration_Start",
        "Duration_End",
        "Compression_Mode",
        "Events_Total",
        "Events_MinDuration",
        "Lines_Count",
        "Lines_MaxCountPerEvent",
        "Title",
        "Encoded_Library",
        "Language",
        "Default",
        "Forced",
    ],
    "Menu": [],
}

TEXT_RAW_FIELD_MAP: dict[str, list[tuple[str, str]]] = {
    "General": [
        ("UniqueID/String", "UniqueID"),
        ("CompleteName", "CompleteName"),
        ("Format/String", "Format"),
        ("Format_Profile", "Format_Profile"),
        ("Format_Version", "Format_Version"),
        ("CodecID/String", "CodecID"),
        ("FileSize/String", "FileSize"),
        ("Duration/String", "Duration"),
        ("OverallBitRate/String", "OverallBitRate"),
        ("FrameRate/String", "FrameRate"),
        ("Title", "Title"),
        ("Encoded_Application/String", "Encoded_Application"),
        ("Encoded_Library/String", "Encoded_Library"),
        ("Comment", "Comment"),
        ("ErrorDetectionType", "extra.ErrorDetectionType"),
    ],
    "Video": [
        ("ID/String", "ID"),
        ("Format/String", "Format"),
        ("Format/Info", "Format_Info"),
        ("Format_Profile", "Format_Profile"),
        ("HDR_Format/String", "HDR_Format"),
        ("Format_Settings", "Format_Settings"),
        ("Format_Settings_CABAC/String", "Format_Settings_CABAC"),
        ("Format_Settings_RefFrames/String", "Format_Settings_RefFrames"),
        ("CodecID", "CodecID"),
        ("CodecID/Info", "CodecID_Info"),
        ("Duration/String", "Duration"),
        ("BitRate/String", "BitRate"),
        ("Width/String", "Width"),
        ("Width_Original/String", "Width_Original"),
        ("Height/String", "Height"),
        ("Height_Original/String", "Height_Original"),
        ("DisplayAspectRatio/String", "DisplayAspectRatio"),
        ("FrameRate_Mode/String", "FrameRate_Mode"),
        ("FrameRate/String", "FrameRate"),
        ("ColorSpace", "ColorSpace"),
        ("ChromaSubsampling/String", "ChromaSubsampling"),
        ("BitDepth/String", "BitDepth"),
        ("ScanType/String", "ScanType"),
        ("Title", "Title"),
        ("Bits-(Pixel*Frame)", "Bits_Pixel_Frame"),
        ("StreamSize/String", "StreamSize"),
        ("Encoded_Library/String", "Encoded_Library"),
        ("Encoded_Library_Settings", "Encoded_Library_Settings"),
        ("Default/String", "Default"),
        ("Forced/String", "Forced"),
        ("colour_range", "colour_range"),
        ("colour_primaries", "colour_primaries"),
        ("transfer_characteristics", "transfer_characteristics"),
        ("matrix_coefficients", "matrix_coefficients"),
        ("MasteringDisplay_ColorPrimaries", "MasteringDisplay_ColorPrimaries"),
        ("MasteringDisplay_Luminance", "MasteringDisplay_Luminance"),
        ("MaxCLL/String", "MaxCLL"),
        ("MaxFALL/String", "MaxFALL"),
        ("CodecConfigurationBox", "CodecConfigurationBox"),
    ],
    "Audio": [
        ("ID/String", "ID"),
        ("Format/String", "Format"),
        ("Format/Info", "Format_Info"),
        ("Format_Commercial_IfAny", "Format_Commercial_IfAny"),
        ("CodecID", "CodecID"),
        ("Duration/String", "Duration"),
        ("Source_Duration/String", "Source_Duration"),
        ("Source_Duration_LastFrame/String", "Source_Duration_LastFrame"),
        ("BitRate_Mode/String", "BitRate_Mode"),
        ("BitRate/String", "BitRate"),
        ("Channel(s)/String", "Channels"),
        ("ChannelLayout", "ChannelLayout"),
        ("SamplingRate/String", "SamplingRate"),
        ("FrameRate/String", "FrameRate"),
        ("BitDepth/String", "BitDepth"),
        ("Compression_Mode/String", "Compression_Mode"),
        ("Title", "Title"),
        ("StreamSize/String", "StreamSize"),
        ("Source_StreamSize/String", "Source_StreamSize"),
        ("Encoded_Library/String", "Encoded_Library"),
        ("Language/String", "Language"),
        ("ServiceKind/String", "ServiceKind"),
        ("Default/String", "Default"),
        ("Forced/String", "Forced"),
        ("AlternateGroup/String", "AlternateGroup"),
        ("dialnorm", "extra.dialnorm"),
        ("dialnorm_Average", "extra.dialnorm_Average"),
        ("dialnorm_Minimum", "extra.dialnorm_Minimum"),
        ("dialnorm_Maximum", "extra.dialnorm_Maximum"),
    ],
    "Text": [
        ("ID/String", "ID"),
        ("Format/String", "Format"),
        ("CodecID", "CodecID"),
        ("CodecID/Info", "CodecID_Info"),
        ("Duration/String", "Duration"),
        ("Duration_End/String", "Duration_End"),
        ("Compression_Mode/String", "Compression_Mode"),
        ("Events_Total", "Events_Total"),
        ("Events_MinDuration/String", "Events_MinDuration"),
        ("Lines_Count", "Lines_Count"),
        ("Lines_MaxCountPerEvent", "Lines_MaxCountPerEvent"),
        ("Title", "Title"),
        ("Encoded_Library/String", "Encoded_Library"),
        ("Language/String", "Language"),
        ("Default/String", "Default"),
        ("Forced/String", "Forced"),
    ],
    "Menu": [],
}
